import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from '@nativescript/angular';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BarChartComponent } from './bar-chart/bar-chart/bar-chart.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import { HeaderComponent } from './header/header.component';
import { SettingComponent } from './setting/setting.component';
import { HomeComponent } from './home/home.component';
import { EquipComponent } from './equip/equip.component';
export const routes: Routes = [
{ path: "", redirectTo: "/auto-generated", pathMatch: "full" },
    { path: "auto-generated", component: AutoGeneratedComponent },
    { path: "setting", component: SettingComponent },
    { path: "sidebar", component: SidebarComponent },
    { path: "home", component: HomeComponent },
    { path: "equip", component: EquipComponent }
];

//  [{
//   path: '',
//   component: AutoGeneratedComponent,
//   children: [
//   { 
//     path: 'setting',
//     component: SettingComponent 
//   },
  
  // ]},];

// [
//   {
//       path: '',
//       redirectTo: '/auto-generated',
//       pathMatch: 'full',
//   },
//   {
//       path: 'auto-generated',
//       component: AutoGeneratedComponent,
//   },
//   {
//     path: '',
//     redirectTo: '/bar-chart',
//     pathMatch: 'full',
// },
// {
//     path: 'bar-chart',
//     component: BarChartComponent,
// },
// {
//   path: '',
//   redirectTo: '/sidebar',
//   pathMatch: 'full',
// },
// {
//   path: 'sidebar',
//   component: SidebarComponent,
// },
// {
//   path: '',
//   redirectTo: '/header',
//   pathMatch: 'full',
// },
// {
//   path: 'header',
//   component: HeaderComponent,
// },
//  {
//    path: '',
//   redirectTo: '/setting',
//   pathMatch: 'full',
//  },
// {
//   path: 'setting',
//   component: SettingComponent,
// },
// ];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
