import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BarChartComponent } from '@src/app/bar-chart/bar-chart/bar-chart.component';
import { NativeScriptUIChartModule } from "nativescript-ui-chart/angular";
import { SidebarComponent } from '@src/app/sidebar/sidebar.component';
import { HeaderComponent } from '@src/app/header/header.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import { HomeComponent } from '@src/app/home/home.component';
import { SettingComponent } from '@src/app/setting/setting.component';
import { SearchComponent } from '@src/app/search/search.component';
import { EquipComponent } from '@src/app/equip/equip.component';

// import { EquippropComponent } from '@src/app/equipprop/equipprop.component';
@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    BarChartComponent,
    SidebarComponent,
    HeaderComponent,
    FooterComponent,
    HomeComponent,
    SettingComponent,
    SearchComponent,
    EquipComponent,

    // EquippropComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NativeScriptUIChartModule,
    HttpClientModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
