import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from '@nativescript/angular';
import { HttpClientModule } from '@angular/common/http';
import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BarChartComponent } from '@src/app/bar-chart/bar-chart/bar-chart.component';
import { NativeScriptUIChartModule } from "nativescript-ui-chart/angular";
import { SidebarComponent } from '@src/app/sidebar/sidebar.component';
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { HeaderComponent } from '@src/app/header/header.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import { HomeComponent } from '@src/app/home/home.component';
import { SettingComponent } from '@src/app/setting/setting.component';
import { SearchComponent } from '@src/app/search/search.component';
import { EquipComponent } from '@src/app/equip/equip.component';

// import { EquippropComponent } from '@src/app/equipprop/equipprop.component';

// Uncomment and add to NgModule imports if you need to use two-way binding and/or HTTP wrapper
// import { NativeScriptFormsModule, NativeScriptHttpClientModule } from '@nativescript/angular';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    BarChartComponent,
    SidebarComponent,
    HeaderComponent,
    FooterComponent,
    HomeComponent,
    SettingComponent,
    SearchComponent,
    EquipComponent,
 
    // EquippropComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    NativeScriptUIChartModule,
    NativeScriptUISideDrawerModule,
    HttpClientModule,
    
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
